### ISSUE TITLE
How to run it after $ npm i

### ISSUE THREAD

**Issue by kul1010** [callthem-online/react-sip#1]
How to run it after $ npm i or install all modules

**Comment by kachkaev** [comment]
Hi @kul1010! We're still in the process of publishing this module properly - it was originally a part of a monolithic web app. Hold on for a few days - we'll make it work!

Also if you have any ideas on what props / features could be useful, feel free to share!

**Comment by kul1010** [comment]
ok sure.

**Comment by kachkaev** [comment]
Hi @kul1010! Feel free to check out the new version – it should work now. Let know what you think here or in a new issue! Closing for now.
